// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using it.lucaporfiri.appweb.core.web.Data;

#nullable disable

namespace it.lucaporfiri.appweb.core.web.Migrations
{
    [DbContext(typeof(ContestoApp))]
    partial class ContestoAppModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("it.lucaporfiri.appweb.core.web.Models.Abbonamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtletaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.ToTable("Abbonamento", (string)null);
                });

            modelBuilder.Entity("it.lucaporfiri.appweb.core.web.Models.Atleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnnoDiNascita")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cognome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataInizioIscrizione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Atleta", (string)null);
                });

            modelBuilder.Entity("it.lucaporfiri.appweb.core.web.Models.Scheda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtletaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.ToTable("Scheda", (string)null);
                });

            modelBuilder.Entity("it.lucaporfiri.appweb.core.web.Models.Abbonamento", b =>
                {
                    b.HasOne("it.lucaporfiri.appweb.core.web.Models.Atleta", "Atleta")
                        .WithMany("Abbonamenti")
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");
                });

            modelBuilder.Entity("it.lucaporfiri.appweb.core.web.Models.Scheda", b =>
                {
                    b.HasOne("it.lucaporfiri.appweb.core.web.Models.Atleta", "Cliente")
                        .WithMany("Schede")
                        .HasForeignKey("AtletaId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("it.lucaporfiri.appweb.core.web.Models.Atleta", b =>
                {
                    b.Navigation("Abbonamenti");

                    b.Navigation("Schede");
                });
#pragma warning restore 612, 618
        }
    }
}
